#!/bin/bash
if [ "$1" = "" ]; then
	echo "missing name"
else
	if [ -d "$1" ]; then
		echo "Already exists"
	else
		mkdir "$1"
		cp makefile "$1"
		cp skel.cpp "$1/$1.cpp"
		sed -i "s/skeleton/$1/g" "$1/makefile"
	fi
fi

